[package]
name = "wasm_emulators"
version = "0.1.0"
authors = ["Affonso Neto"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"]}
